---
apiVersion: v2
name: peertube
description: |
  Free software to take back control of your videos

  NB; With the 1.0 release, the names for existing SMTP secrets have been changed/fixed.
icon: https://upload.wikimedia.org/wikipedia/commons/2/2b/Logo_de_PeerTube.svg
appVersion: 6.3.0

type: application
version: 1.4.0
maintainers:
  - name: Alexander Olofsson
    email: ace@haxalot.com

dependencies:
  - name: postgresql
    version: ^12.1.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: ^17.3.17
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
